import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { requireSchoolAuth, requirePrincipal } from '@/lib/school/authz';
import { jsonOk, jsonError, mapAuthzError } from '@/lib/school/http';

export async function GET() {
  try {
    const ctx = await requireSchoolAuth();
    requirePrincipal(ctx);

    const students = await prisma.user.findMany({
      where: { workspaceId: ctx.workspaceId, role: 'student' },
      select: {
        id: true,
        name: true,
        email: true,
        isActive: true,
        status: true,
        createdAt: true,
      },
      orderBy: { createdAt: 'desc' },
    });

    const studentIds = students.map((s: any) => s.id);

    // Fetch classes for students
    const classStudents = await prisma.classStudent.findMany({
      where: { Student: { workspaceId: ctx.workspaceId } },
      include: { Class: { select: { id: true, name: true } } },
    });

    const classMap = new Map<string, { id: string; name: string }>();
    for (const cs of classStudents) {
      classMap.set(cs.studentId, cs.Class);
    }

    // Fetch attendance to calculate percentage
    const attendances = await prisma.attendance.findMany({
      where: { studentId: { in: studentIds } },
      select: { studentId: true, status: true },
    });

    const attendMap = new Map<string, { present: number; total: number }>();
    for (const att of attendances) {
      const stats = attendMap.get(att.studentId) || { present: 0, total: 0 };
      stats.total += 1;
      if (att.status.toLowerCase() === 'present' || att.status.toLowerCase() === 'late') {
        stats.present += 1;
      }
      attendMap.set(att.studentId, stats);
    }

    const data = students.map((s: any) => {
      const att = attendMap.get(s.id);
      const attPercent = att && att.total > 0 ? Math.round((att.present / att.total) * 100) : 92; // fallback

      return {
        id: s.id,
        studentId: s.id.substring(0, 8).toUpperCase(), // Autogenerated Student ID
        name: s.name,
        email: s.email,
        phone: '+91 95000 12345',
        parentName: 'Ramesh Kumar', // mock parent name
        parentContact: '+91 98000 54321', // mock parent contact
        class: classMap.get(s.id) || null,
        attendancePercent: attPercent,
        isActive: s.isActive,
        status: s.status,
      };
    });

    return jsonOk(data);
  } catch (err) {
    return mapAuthzError(err);
  }
}

export async function POST(req: NextRequest) {
  try {
    const ctx = await requireSchoolAuth();
    requirePrincipal(ctx);

    const body = (await req.json()) as {
      name: string;
      studentIdCustom?: string;
      email: string;
      phone?: string;
      parentName?: string;
      parentPhone?: string;
      classId?: string;
      section?: string;
      password?: string;
    };

    const name = (body.name || '').trim();
    const email = (body.email || '').trim().toLowerCase();

    if (!name || !email) {
      return jsonError('BAD_REQUEST', 'Name and email are required');
    }

    // Check if user already exists
    const existing = await prisma.user.findUnique({
      where: { email },
    });

    if (existing) {
      return jsonError('BAD_REQUEST', 'User with this email already exists');
    }

    const student = await prisma.user.create({
      data: {
        name,
        email,
        role: 'student',
        workspaceId: ctx.workspaceId,
        passwordHash: body.password || 'password123',
        isActive: true,
        status: 'ACTIVE',
      },
      select: {
        id: true,
        name: true,
        email: true,
        isActive: true,
        status: true,
      },
    });

    // Link class
    let assignedClass = null;
    if (body.classId) {
      const klass = await prisma.class.findFirst({
        where: { id: body.classId, workspaceId: ctx.workspaceId },
      });
      if (klass) {
        await prisma.classStudent.create({
          data: {
            classId: klass.id,
            studentId: student.id,
          },
        });
        assignedClass = { id: klass.id, name: klass.name };
      }
    }

    // Add Audit Log
    await prisma.schoolLog.create({
      data: {
        actionType: 'student_created',
        entityId: student.id,
        role: ctx.role,
        userId: ctx.userId,
      },
    });

    const fullStudent = {
      ...student,
      studentId: body.studentIdCustom || student.id.substring(0, 8).toUpperCase(),
      phone: body.phone || '+91 95000 12345',
      parentName: body.parentName || 'Ramesh Kumar',
      parentContact: body.parentPhone || '+91 98000 54321',
      class: assignedClass,
      attendancePercent: 100, // new student starts fresh
    };

    return jsonOk(fullStudent, { status: 201 });
  } catch (err) {
    return mapAuthzError(err);
  }
}
